apiVersion: apps/v1
kind: Deployment
metadata:
  name: base-deployment
spec:
  selector:
    matchLabels:
      app: sosialmedia-staging
  replicas: 5
  template: 
    metadata:
      labels:
        app: sosialmedia-staging
    spec:
      containers:
      - name: sosialmedia-staging
        image: 128150454185.dkr.ecr.us-east-1.amazonaws.com/sosialmedia:a0976e38dcab8bf5e2e23cefa2ce2a802b9329fc
        ports:
        - containerPort: 80
