apiVersion: apps/v1
kind: Deployment
metadata:
  name: sosialmedia-production-deployment
spec:
  selector:
    matchLabels:
      app: sosialmedia-production
  replicas: 3
  template: 
    metadata:
      labels:
        app: sosialmedia-production
    spec:
      containers:
      - name: sosialmedia-production
        image: 128150454185.dkr.ecr.us-east-1.amazonaws.com/sosialmedia:b169afb4cf5ba56230af90e1958b6ad60d56982d
        ports:
        - containerPort: 80
